name: Preview deploy to Firebase Hosting on PR

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

# Cancel in-flight preview builds for the same PR to save time
concurrency:
  group: preview-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write  # so we can comment the preview URL

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # OPTIONAL: only keep if your app reads NEXT_PUBLIC_* from .env.local
      - name: Create .env.local from repo variables
        run: |
          cat > .env.local << 'EOF'
          NEXT_PUBLIC_FB_API_KEY=${{ vars.NEXT_PUBLIC_FB_API_KEY }}
          NEXT_PUBLIC_FB_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FB_AUTH_DOMAIN }}
          NEXT_PUBLIC_FB_DB_URL=${{ vars.NEXT_PUBLIC_FB_DB_URL }}
          NEXT_PUBLIC_FB_PROJECT_ID=${{ vars.NEXT_PUBLIC_FB_PROJECT_ID }}
          NEXT_PUBLIC_FB_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FB_STORAGE_BUCKET }}
          NEXT_PUBLIC_FB_APP_ID=${{ vars.NEXT_PUBLIC_FB_APP_ID }}
          EOF

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build (Next.js export to /out)
        run: pnpm build

      - name: Deploy preview to Firebase Hosting
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSCORES }}
          projectId: joyscores
          target: joyscores-ef086       # your Hosting site id
          channelId: pr-${{ github.event.pull_request.number }}
          expires: 7d                   # auto-delete after 7 days

      - name: Comment preview URL on PR
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = core.getInput('details_url', { required: false }) || '${{ steps.deploy.outputs.details_url }}';
            const msg = `🚀 **Preview deployed**\n\n🔗 ${url}\n\n_This preview will auto-expire in 7 days or when the PR closes._`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: msg
            });
