name: Preview (Firebase Hosting)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write
  pull-requests: write
  deployments: write
  id-token: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      # === IMPORTANT: set channelId + project/site ===
   - name: Firebase Hosting deploy (preview)
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: ${{ secrets.GITHUB_TOKEN }}
    # Always-resolves channel id (works on re-runs too)
    channelId: preview-${{ github.sha }}
    projectId: joyscores            # from your log
    site: joyscores-ef086           # from your log
    expires: 7d
    # If you prefer service account auth instead of OIDC, use the next line instead of projectId/site:
    # firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSCORES }}
