name: Preview (Firebase Hosting via CLI)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_ID: joyscores            # from your logs
  SITE_ID: joyscores-ef086         # from your logs
  CHANNEL_ID: preview-${{ github.sha }}
  EXPIRES: 7d

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      # Auth: write Service Account JSON to a file and point GOOGLE_APPLICATION_CREDENTIALS at it
      - name: Write Firebase service account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSCORES }}' > $HOME/sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/sa.json" >> $GITHUB_ENV

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@14

      - name: Deploy preview channel (explicit channelId)
        id: deploy
        run: |
          set -e
          # Deploy and capture JSON
          OUT=$(firebase hosting:channel:deploy "$CHANNEL_ID" \
                --project "$PROJECT_ID" --site "$SITE_ID" \
                --expires "$EXPIRES" --json)
          echo "$OUT"
          # Extract the URL with jq (installed on ubuntu-latest)
          URL=$(echo "$OUT" | jq -r '.result[]?.url // .result.channel.url // empty')
          if [ -z "$URL" ]; then
            echo "Preview URL not found in CLI output"; exit 1
          fi
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = core.getInput('url') || process.env.URL;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ Firebase Preview: ${url}`
            });
        env:
          URL: ${{ steps.deploy.outputs.url }}
        with:
          url: ${{ steps.deploy.outputs.url }}
