name: Preview (Firebase Hosting)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

concurrency:
  group: preview-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Create .env.local from repo variables
        run: |
          cat > .env.local << 'EOF'
          NEXT_PUBLIC_FB_API_KEY=${{ vars.NEXT_PUBLIC_FB_API_KEY }}
          NEXT_PUBLIC_FB_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FB_AUTH_DOMAIN }}
          NEXT_PUBLIC_FB_DB_URL=${{ vars.NEXT_PUBLIC_FB_DB_URL }}
          NEXT_PUBLIC_FB_PROJECT_ID=${{ vars.NEXT_PUBLIC_FB_PROJECT_ID }}
          NEXT_PUBLIC_FB_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FB_STORAGE_BUCKET }}
          NEXT_PUBLIC_FB_APP_ID=${{ vars.NEXT_PUBLIC_FB_APP_ID }}
          EOF

      # ⬇⬇⬇ THIS LINE CHANGED
      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build (Next.js static export)
        run: pnpm build

      - name: Sanity – exported routes
        run: |
          echo "---- out/ ----"
          if [ -d out ]; then
            find out -maxdepth 2 -type f -name "index.html" | sed 's#^out##' | sort
          else
            echo "::error ::No 'out/' directory produced by build."
            exit 1
          fi

      - name: Deploy PR preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSCORES }}
          projectId: joyscores
          site: joyscores-ef086
          channelId: pr-${{ github.event.pull_request.number }}
          expires: 7d

      - name: Deploy manual preview
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSCORES }}
          projectId: joyscores
          site: joyscores-ef086
          channelId: preview-${{ github.sha }}
          expires: 7d
